### ISSUE TITLE
Add a rendering of the PCB

### ISSUE THREAD

**Issue by probonopd** [mzuelch/CATs-Desktopsynth#1]
Hello @mzuelch, thanks for this cool project! I posted it in the [MiniDexed Discussions](https://github.com/probonopd/MiniDexed/discussions/273) forum.

Maybe you'd like to add a rendering of the PCB to the README.md, like this:

![image](https://user-images.githubusercontent.com/2480569/172060253-b76661c2-e14c-47ab-aeee-8782541a9034.png)

Made with https://www.pcbway.com/project/OnlineGerberViewer.html

**Comment by mzuelch** [comment]
I'm about to document my working build - renderings of the addon board included of course.

**Comment by mzuelch** [comment]
https://tracespace.io seems to be a little bit more appropriate for an open source project :)

done.
